# .streamlit/secrets.toml
[firebase]
apiKey = "AIzaSyDGXbp0ki5MiJxkR6E10oZZ2IbkwSrsH40"
authDomain = "qotframework.firebaseapp.com"
projectId = "qotframework"
storageBucket = "qotframework.firebasestorage.app"
messagingSenderId = "56504362452"
appId = "1:56504362452:web:3b0600e286732780e8a241"
databaseURL = "" # 🔥 Add this line!